<?php

declare(strict_types=1);

namespace Cam5\Domoarigato\Enums;

use Cam5\Domoarigato\Attributes as Attr;

/**
 * Static Enum of attributes explicitly supported.
 *
 * This is every attribute in the index of the HTML Living Standard, plus its event handler
 * content attributes. Anything else ("data-*", "aria-*", attributes of your own) still works,
 * and is treated as a simple key-value pair.
 *
 * @see https://html.spec.whatwg.org/multipage/indices.html#attributes-3
 */
class Attributes extends StaticEnum
{
    const ABBR                            = 'abbr';
    const ACCEPT                          = 'accept';
    const ACCEPT_CHARSET                  = 'accept-charset';
    const ACCESSKEY                       = 'accesskey';
    const ACTION                          = 'action';
    const ALLOW                           = 'allow';
    const ALLOWFULLSCREEN                 = 'allowfullscreen';
    const ALPHA                           = 'alpha';
    const ALT                             = 'alt';
    const AS                              = 'as';
    const ASYNC                           = 'async';
    const AUTOCAPITALIZE                  = 'autocapitalize';
    const AUTOCOMPLETE                    = 'autocomplete';
    const AUTOCORRECT                     = 'autocorrect';
    const AUTOFOCUS                       = 'autofocus';
    const AUTOPLAY                        = 'autoplay';
    const BLOCKING                        = 'blocking';
    const CHARSET                         = 'charset';
    const CHECKED                         = 'checked';
    const CITE                            = 'cite';
    const ATTR_CLASS                      = 'class';
    const CLOSEDBY                        = 'closedby';
    const COLOR                           = 'color';
    const COLORSPACE                      = 'colorspace';
    const COLS                            = 'cols';
    const COLSPAN                         = 'colspan';
    const COMMAND                         = 'command';
    const COMMANDFOR                      = 'commandfor';
    const CONTENT                         = 'content';
    const CONTENTEDITABLE                 = 'contenteditable';
    const CONTROLS                        = 'controls';
    const COORDS                          = 'coords';
    const CROSSORIGIN                     = 'crossorigin';
    const DATA                            = 'data';
    const DATETIME                        = 'datetime';
    const DECODING                        = 'decoding';
    const DEFAULT                         = 'default';
    const DEFER                           = 'defer';
    const DIR                             = 'dir';
    const DIRNAME                         = 'dirname';
    const DISABLED                        = 'disabled';
    const DOWNLOAD                        = 'download';
    const DRAGGABLE                       = 'draggable';
    const ENCTYPE                         = 'enctype';
    const ENTERKEYHINT                    = 'enterkeyhint';
    const FETCHPRIORITY                   = 'fetchpriority';
    const FOR                             = 'for';
    const FORM                            = 'form';
    const FORMACTION                      = 'formaction';
    const FORMENCTYPE                     = 'formenctype';
    const FORMMETHOD                      = 'formmethod';
    const FORMNOVALIDATE                  = 'formnovalidate';
    const FORMTARGET                      = 'formtarget';
    const HEADERS                         = 'headers';
    const HEADINGOFFSET                   = 'headingoffset';
    const HEADINGRESET                    = 'headingreset';
    const HEIGHT                          = 'height';
    const HIDDEN                          = 'hidden';
    const HIGH                            = 'high';
    const HREF                            = 'href';
    const HREFLANG                        = 'hreflang';
    const HTTP_EQUIV                      = 'http-equiv';
    const ID                              = 'id';
    const IMAGESIZES                      = 'imagesizes';
    const IMAGESRCSET                     = 'imagesrcset';
    const INERT                           = 'inert';
    const INPUTMODE                       = 'inputmode';
    const INTEGRITY                       = 'integrity';
    const IS                              = 'is';
    const ISMAP                           = 'ismap';
    const ITEMID                          = 'itemid';
    const ITEMPROP                        = 'itemprop';
    const ITEMREF                         = 'itemref';
    const ITEMSCOPE                       = 'itemscope';
    const ITEMTYPE                        = 'itemtype';
    const KIND                            = 'kind';
    const LABEL                           = 'label';
    const LANG                            = 'lang';
    const LIST                            = 'list';
    const LOADING                         = 'loading';
    const LOOP                            = 'loop';
    const LOW                             = 'low';
    const MAX                             = 'max';
    const MAXLENGTH                       = 'maxlength';
    const MEDIA                           = 'media';
    const METHOD                          = 'method';
    const MIN                             = 'min';
    const MINLENGTH                       = 'minlength';
    const MULTIPLE                        = 'multiple';
    const MUTED                           = 'muted';
    const NAME                            = 'name';
    const NOMODULE                        = 'nomodule';
    const NONCE                           = 'nonce';
    const NOVALIDATE                      = 'novalidate';
    const OPEN                            = 'open';
    const OPTIMUM                         = 'optimum';
    const PATTERN                         = 'pattern';
    const PING                            = 'ping';
    const PLACEHOLDER                     = 'placeholder';
    const PLAYSINLINE                     = 'playsinline';
    const POPOVER                         = 'popover';
    const POPOVERTARGET                   = 'popovertarget';
    const POPOVERTARGETACTION             = 'popovertargetaction';
    const POSTER                          = 'poster';
    const PRELOAD                         = 'preload';
    const READONLY                        = 'readonly';
    const REFERRERPOLICY                  = 'referrerpolicy';
    const REL                             = 'rel';
    const REQUIRED                        = 'required';
    const REVERSED                        = 'reversed';
    const ROWS                            = 'rows';
    const ROWSPAN                         = 'rowspan';
    const SANDBOX                         = 'sandbox';
    const SCOPE                           = 'scope';
    const SELECTED                        = 'selected';
    const SHADOWROOTCLONABLE              = 'shadowrootclonable';
    const SHADOWROOTCUSTOMELEMENTREGISTRY = 'shadowrootcustomelementregistry';
    const SHADOWROOTDELEGATESFOCUS        = 'shadowrootdelegatesfocus';
    const SHADOWROOTMODE                  = 'shadowrootmode';
    const SHADOWROOTSERIALIZABLE          = 'shadowrootserializable';
    const SHADOWROOTSLOTASSIGNMENT        = 'shadowrootslotassignment';
    const SHAPE                           = 'shape';
    const SIZE                            = 'size';
    const SIZES                           = 'sizes';
    const SLOT                            = 'slot';
    const SPAN                            = 'span';
    const SPELLCHECK                      = 'spellcheck';
    const SRC                             = 'src';
    const SRCDOC                          = 'srcdoc';
    const SRCLANG                         = 'srclang';
    const SRCSET                          = 'srcset';
    const START                           = 'start';
    const STEP                            = 'step';
    const STYLE                           = 'style';
    const TABINDEX                        = 'tabindex';
    const TARGET                          = 'target';
    const TITLE                           = 'title';
    const TRANSLATE                       = 'translate';
    const TYPE                            = 'type';
    const USEMAP                          = 'usemap';
    const VALUE                           = 'value';
    const WIDTH                           = 'width';
    const WRAP                            = 'wrap';
    const WRITINGSUGGESTIONS              = 'writingsuggestions';

    // Event handler content attributes.
    const ONAFTERPRINT                    = 'onafterprint';
    const ONAUXCLICK                      = 'onauxclick';
    const ONBEFOREINPUT                   = 'onbeforeinput';
    const ONBEFOREMATCH                   = 'onbeforematch';
    const ONBEFOREPRINT                   = 'onbeforeprint';
    const ONBEFOREUNLOAD                  = 'onbeforeunload';
    const ONBEFORETOGGLE                  = 'onbeforetoggle';
    const ONBLUR                          = 'onblur';
    const ONCANCEL                        = 'oncancel';
    const ONCANPLAY                       = 'oncanplay';
    const ONCANPLAYTHROUGH                = 'oncanplaythrough';
    const ONCHANGE                        = 'onchange';
    const ONCLICK                         = 'onclick';
    const ONCLOSE                         = 'onclose';
    const ONCOMMAND                       = 'oncommand';
    const ONCONTEXTLOST                   = 'oncontextlost';
    const ONCONTEXTMENU                   = 'oncontextmenu';
    const ONCONTEXTRESTORED               = 'oncontextrestored';
    const ONCOPY                          = 'oncopy';
    const ONCUECHANGE                     = 'oncuechange';
    const ONCUT                           = 'oncut';
    const ONDBLCLICK                      = 'ondblclick';
    const ONDRAG                          = 'ondrag';
    const ONDRAGEND                       = 'ondragend';
    const ONDRAGENTER                     = 'ondragenter';
    const ONDRAGLEAVE                     = 'ondragleave';
    const ONDRAGOVER                      = 'ondragover';
    const ONDRAGSTART                     = 'ondragstart';
    const ONDROP                          = 'ondrop';
    const ONDURATIONCHANGE                = 'ondurationchange';
    const ONEMPTIED                       = 'onemptied';
    const ONENDED                         = 'onended';
    const ONERROR                         = 'onerror';
    const ONFOCUS                         = 'onfocus';
    const ONFORMDATA                      = 'onformdata';
    const ONHASHCHANGE                    = 'onhashchange';
    const ONINPUT                         = 'oninput';
    const ONINVALID                       = 'oninvalid';
    const ONKEYDOWN                       = 'onkeydown';
    const ONKEYPRESS                      = 'onkeypress';
    const ONKEYUP                         = 'onkeyup';
    const ONLANGUAGECHANGE                = 'onlanguagechange';
    const ONLOAD                          = 'onload';
    const ONLOADEDDATA                    = 'onloadeddata';
    const ONLOADEDMETADATA                = 'onloadedmetadata';
    const ONLOADSTART                     = 'onloadstart';
    const ONMESSAGE                       = 'onmessage';
    const ONMESSAGEERROR                  = 'onmessageerror';
    const ONMOUSEDOWN                     = 'onmousedown';
    const ONMOUSEENTER                    = 'onmouseenter';
    const ONMOUSELEAVE                    = 'onmouseleave';
    const ONMOUSEMOVE                     = 'onmousemove';
    const ONMOUSEOUT                      = 'onmouseout';
    const ONMOUSEOVER                     = 'onmouseover';
    const ONMOUSEUP                       = 'onmouseup';
    const ONOFFLINE                       = 'onoffline';
    const ONONLINE                        = 'ononline';
    const ONPAGEHIDE                      = 'onpagehide';
    const ONPAGEREVEAL                    = 'onpagereveal';
    const ONPAGESHOW                      = 'onpageshow';
    const ONPAGESWAP                      = 'onpageswap';
    const ONPASTE                         = 'onpaste';
    const ONPAUSE                         = 'onpause';
    const ONPLAY                          = 'onplay';
    const ONPLAYING                       = 'onplaying';
    const ONPOPSTATE                      = 'onpopstate';
    const ONPROGRESS                      = 'onprogress';
    const ONRATECHANGE                    = 'onratechange';
    const ONRESET                         = 'onreset';
    const ONRESIZE                        = 'onresize';
    const ONREJECTIONHANDLED              = 'onrejectionhandled';
    const ONSCROLL                        = 'onscroll';
    const ONSCROLLEND                     = 'onscrollend';
    const ONSECURITYPOLICYVIOLATION       = 'onsecuritypolicyviolation';
    const ONSEEKED                        = 'onseeked';
    const ONSEEKING                       = 'onseeking';
    const ONSELECT                        = 'onselect';
    const ONSLOTCHANGE                    = 'onslotchange';
    const ONSTALLED                       = 'onstalled';
    const ONSTORAGE                       = 'onstorage';
    const ONSUBMIT                        = 'onsubmit';
    const ONSUSPEND                       = 'onsuspend';
    const ONTIMEUPDATE                    = 'ontimeupdate';
    const ONTOGGLE                        = 'ontoggle';
    const ONUNHANDLEDREJECTION            = 'onunhandledrejection';
    const ONUNLOAD                        = 'onunload';
    const ONVOLUMECHANGE                  = 'onvolumechange';
    const ONWAITING                       = 'onwaiting';
    const ONWHEEL                         = 'onwheel';

    /**
     * Map of names to classnames.
     *
     * @var array
     */
    protected static array $keys = [
        self::ABBR                            => Attr\SimpleAttribute::class,
        self::ACCEPT                          => Attr\CommaSeparatedAttribute::class,
        self::ACCEPT_CHARSET                  => Attr\SimpleAttribute::class,
        self::ACCESSKEY                       => Attr\CollectionAttribute::class,
        self::ACTION                          => Attr\SimpleAttribute::class,
        self::ALLOW                           => Attr\SimpleAttribute::class,
        self::ALLOWFULLSCREEN                 => Attr\BooleanAttribute::class,
        self::ALPHA                           => Attr\BooleanAttribute::class,
        self::ALT                             => Attr\SimpleAttribute::class,
        self::AS                              => Attr\SimpleAttribute::class,
        self::ASYNC                           => Attr\BooleanAttribute::class,
        self::AUTOCAPITALIZE                  => Attr\SimpleAttribute::class,
        self::AUTOCOMPLETE                    => Attr\CollectionAttribute::class,
        self::AUTOCORRECT                     => Attr\OnOffAttribute::class,
        self::AUTOFOCUS                       => Attr\BooleanAttribute::class,
        self::AUTOPLAY                        => Attr\BooleanAttribute::class,
        self::BLOCKING                        => Attr\CollectionAttribute::class,
        self::CHARSET                         => Attr\SimpleAttribute::class,
        self::CHECKED                         => Attr\BooleanAttribute::class,
        self::CITE                            => Attr\SimpleAttribute::class,
        self::ATTR_CLASS                      => Attr\CollectionAttribute::class,
        self::CLOSEDBY                        => Attr\SimpleAttribute::class,
        self::COLOR                           => Attr\SimpleAttribute::class,
        self::COLORSPACE                      => Attr\SimpleAttribute::class,
        self::COLS                            => Attr\SimpleAttribute::class,
        self::COLSPAN                         => Attr\SimpleAttribute::class,
        self::COMMAND                         => Attr\SimpleAttribute::class,
        self::COMMANDFOR                      => Attr\SimpleAttribute::class,
        self::CONTENT                         => Attr\SimpleAttribute::class,
        self::CONTENTEDITABLE                 => Attr\TrueFalseAttribute::class,
        self::CONTROLS                        => Attr\BooleanAttribute::class,
        self::COORDS                          => Attr\CommaSeparatedAttribute::class,
        self::CROSSORIGIN                     => Attr\SimpleAttribute::class,
        self::DATA                            => Attr\SimpleAttribute::class,
        self::DATETIME                        => Attr\SimpleAttribute::class,
        self::DECODING                        => Attr\SimpleAttribute::class,
        self::DEFAULT                         => Attr\BooleanAttribute::class,
        self::DEFER                           => Attr\BooleanAttribute::class,
        self::DIR                             => Attr\SimpleAttribute::class,
        self::DIRNAME                         => Attr\SimpleAttribute::class,
        self::DISABLED                        => Attr\BooleanAttribute::class,
        self::DOWNLOAD                        => Attr\SimpleAttribute::class,
        self::DRAGGABLE                       => Attr\TrueFalseAttribute::class,
        self::ENCTYPE                         => Attr\SimpleAttribute::class,
        self::ENTERKEYHINT                    => Attr\SimpleAttribute::class,
        self::FETCHPRIORITY                   => Attr\SimpleAttribute::class,
        self::FOR                             => Attr\SimpleAttribute::class,
        self::FORM                            => Attr\SimpleAttribute::class,
        self::FORMACTION                      => Attr\SimpleAttribute::class,
        self::FORMENCTYPE                     => Attr\SimpleAttribute::class,
        self::FORMMETHOD                      => Attr\SimpleAttribute::class,
        self::FORMNOVALIDATE                  => Attr\BooleanAttribute::class,
        self::FORMTARGET                      => Attr\SimpleAttribute::class,
        self::HEADERS                         => Attr\CollectionAttribute::class,
        self::HEADINGOFFSET                   => Attr\SimpleAttribute::class,
        self::HEADINGRESET                    => Attr\BooleanAttribute::class,
        self::HEIGHT                          => Attr\SimpleAttribute::class,
        self::HIDDEN                          => Attr\SimpleAttribute::class,
        self::HIGH                            => Attr\SimpleAttribute::class,
        self::HREF                            => Attr\SimpleAttribute::class,
        self::HREFLANG                        => Attr\SimpleAttribute::class,
        self::HTTP_EQUIV                      => Attr\SimpleAttribute::class,
        self::ID                              => Attr\SimpleAttribute::class,
        self::IMAGESIZES                      => Attr\SimpleAttribute::class,
        self::IMAGESRCSET                     => Attr\CommaSeparatedAttribute::class,
        self::INERT                           => Attr\BooleanAttribute::class,
        self::INPUTMODE                       => Attr\SimpleAttribute::class,
        self::INTEGRITY                       => Attr\SimpleAttribute::class,
        self::IS                              => Attr\SimpleAttribute::class,
        self::ISMAP                           => Attr\BooleanAttribute::class,
        self::ITEMID                          => Attr\SimpleAttribute::class,
        self::ITEMPROP                        => Attr\CollectionAttribute::class,
        self::ITEMREF                         => Attr\CollectionAttribute::class,
        self::ITEMSCOPE                       => Attr\BooleanAttribute::class,
        self::ITEMTYPE                        => Attr\CollectionAttribute::class,
        self::KIND                            => Attr\SimpleAttribute::class,
        self::LABEL                           => Attr\SimpleAttribute::class,
        self::LANG                            => Attr\SimpleAttribute::class,
        self::LIST                            => Attr\SimpleAttribute::class,
        self::LOADING                         => Attr\SimpleAttribute::class,
        self::LOOP                            => Attr\BooleanAttribute::class,
        self::LOW                             => Attr\SimpleAttribute::class,
        self::MAX                             => Attr\SimpleAttribute::class,
        self::MAXLENGTH                       => Attr\SimpleAttribute::class,
        self::MEDIA                           => Attr\SimpleAttribute::class,
        self::METHOD                          => Attr\SimpleAttribute::class,
        self::MIN                             => Attr\SimpleAttribute::class,
        self::MINLENGTH                       => Attr\SimpleAttribute::class,
        self::MULTIPLE                        => Attr\BooleanAttribute::class,
        self::MUTED                           => Attr\BooleanAttribute::class,
        self::NAME                            => Attr\SimpleAttribute::class,
        self::NOMODULE                        => Attr\BooleanAttribute::class,
        self::NONCE                           => Attr\SimpleAttribute::class,
        self::NOVALIDATE                      => Attr\BooleanAttribute::class,
        self::OPEN                            => Attr\BooleanAttribute::class,
        self::OPTIMUM                         => Attr\SimpleAttribute::class,
        self::PATTERN                         => Attr\SimpleAttribute::class,
        self::PING                            => Attr\CollectionAttribute::class,
        self::PLACEHOLDER                     => Attr\SimpleAttribute::class,
        self::PLAYSINLINE                     => Attr\BooleanAttribute::class,
        self::POPOVER                         => Attr\SimpleAttribute::class,
        self::POPOVERTARGET                   => Attr\SimpleAttribute::class,
        self::POPOVERTARGETACTION             => Attr\SimpleAttribute::class,
        self::POSTER                          => Attr\SimpleAttribute::class,
        self::PRELOAD                         => Attr\SimpleAttribute::class,
        self::READONLY                        => Attr\BooleanAttribute::class,
        self::REFERRERPOLICY                  => Attr\SimpleAttribute::class,
        self::REL                             => Attr\CollectionAttribute::class,
        self::REQUIRED                        => Attr\BooleanAttribute::class,
        self::REVERSED                        => Attr\BooleanAttribute::class,
        self::ROWS                            => Attr\SimpleAttribute::class,
        self::ROWSPAN                         => Attr\SimpleAttribute::class,
        self::SANDBOX                         => Attr\CollectionAttribute::class,
        self::SCOPE                           => Attr\SimpleAttribute::class,
        self::SELECTED                        => Attr\BooleanAttribute::class,
        self::SHADOWROOTCLONABLE              => Attr\BooleanAttribute::class,
        self::SHADOWROOTCUSTOMELEMENTREGISTRY => Attr\BooleanAttribute::class,
        self::SHADOWROOTDELEGATESFOCUS        => Attr\BooleanAttribute::class,
        self::SHADOWROOTMODE                  => Attr\SimpleAttribute::class,
        self::SHADOWROOTSERIALIZABLE          => Attr\BooleanAttribute::class,
        self::SHADOWROOTSLOTASSIGNMENT        => Attr\SimpleAttribute::class,
        self::SHAPE                           => Attr\SimpleAttribute::class,
        self::SIZE                            => Attr\SimpleAttribute::class,
        self::SIZES                           => Attr\SimpleAttribute::class,
        self::SLOT                            => Attr\SimpleAttribute::class,
        self::SPAN                            => Attr\SimpleAttribute::class,
        self::SPELLCHECK                      => Attr\TrueFalseAttribute::class,
        self::SRC                             => Attr\SimpleAttribute::class,
        self::SRCDOC                          => Attr\SimpleAttribute::class,
        self::SRCLANG                         => Attr\SimpleAttribute::class,
        self::SRCSET                          => Attr\CommaSeparatedAttribute::class,
        self::START                           => Attr\SimpleAttribute::class,
        self::STEP                            => Attr\SimpleAttribute::class,
        self::STYLE                           => Attr\SimpleAttribute::class,
        self::TABINDEX                        => Attr\SimpleAttribute::class,
        self::TARGET                          => Attr\SimpleAttribute::class,
        self::TITLE                           => Attr\SimpleAttribute::class,
        self::TRANSLATE                       => Attr\YesNoAttribute::class,
        self::TYPE                            => Attr\SimpleAttribute::class,
        self::USEMAP                          => Attr\SimpleAttribute::class,
        self::VALUE                           => Attr\SimpleAttribute::class,
        self::WIDTH                           => Attr\SimpleAttribute::class,
        self::WRAP                            => Attr\SimpleAttribute::class,
        self::WRITINGSUGGESTIONS              => Attr\TrueFalseAttribute::class,

        self::ONAFTERPRINT                    => Attr\SimpleAttribute::class,
        self::ONAUXCLICK                      => Attr\SimpleAttribute::class,
        self::ONBEFOREINPUT                   => Attr\SimpleAttribute::class,
        self::ONBEFOREMATCH                   => Attr\SimpleAttribute::class,
        self::ONBEFOREPRINT                   => Attr\SimpleAttribute::class,
        self::ONBEFOREUNLOAD                  => Attr\SimpleAttribute::class,
        self::ONBEFORETOGGLE                  => Attr\SimpleAttribute::class,
        self::ONBLUR                          => Attr\SimpleAttribute::class,
        self::ONCANCEL                        => Attr\SimpleAttribute::class,
        self::ONCANPLAY                       => Attr\SimpleAttribute::class,
        self::ONCANPLAYTHROUGH                => Attr\SimpleAttribute::class,
        self::ONCHANGE                        => Attr\SimpleAttribute::class,
        self::ONCLICK                         => Attr\SimpleAttribute::class,
        self::ONCLOSE                         => Attr\SimpleAttribute::class,
        self::ONCOMMAND                       => Attr\SimpleAttribute::class,
        self::ONCONTEXTLOST                   => Attr\SimpleAttribute::class,
        self::ONCONTEXTMENU                   => Attr\SimpleAttribute::class,
        self::ONCONTEXTRESTORED               => Attr\SimpleAttribute::class,
        self::ONCOPY                          => Attr\SimpleAttribute::class,
        self::ONCUECHANGE                     => Attr\SimpleAttribute::class,
        self::ONCUT                           => Attr\SimpleAttribute::class,
        self::ONDBLCLICK                      => Attr\SimpleAttribute::class,
        self::ONDRAG                          => Attr\SimpleAttribute::class,
        self::ONDRAGEND                       => Attr\SimpleAttribute::class,
        self::ONDRAGENTER                     => Attr\SimpleAttribute::class,
        self::ONDRAGLEAVE                     => Attr\SimpleAttribute::class,
        self::ONDRAGOVER                      => Attr\SimpleAttribute::class,
        self::ONDRAGSTART                     => Attr\SimpleAttribute::class,
        self::ONDROP                          => Attr\SimpleAttribute::class,
        self::ONDURATIONCHANGE                => Attr\SimpleAttribute::class,
        self::ONEMPTIED                       => Attr\SimpleAttribute::class,
        self::ONENDED                         => Attr\SimpleAttribute::class,
        self::ONERROR                         => Attr\SimpleAttribute::class,
        self::ONFOCUS                         => Attr\SimpleAttribute::class,
        self::ONFORMDATA                      => Attr\SimpleAttribute::class,
        self::ONHASHCHANGE                    => Attr\SimpleAttribute::class,
        self::ONINPUT                         => Attr\SimpleAttribute::class,
        self::ONINVALID                       => Attr\SimpleAttribute::class,
        self::ONKEYDOWN                       => Attr\SimpleAttribute::class,
        self::ONKEYPRESS                      => Attr\SimpleAttribute::class,
        self::ONKEYUP                         => Attr\SimpleAttribute::class,
        self::ONLANGUAGECHANGE                => Attr\SimpleAttribute::class,
        self::ONLOAD                          => Attr\SimpleAttribute::class,
        self::ONLOADEDDATA                    => Attr\SimpleAttribute::class,
        self::ONLOADEDMETADATA                => Attr\SimpleAttribute::class,
        self::ONLOADSTART                     => Attr\SimpleAttribute::class,
        self::ONMESSAGE                       => Attr\SimpleAttribute::class,
        self::ONMESSAGEERROR                  => Attr\SimpleAttribute::class,
        self::ONMOUSEDOWN                     => Attr\SimpleAttribute::class,
        self::ONMOUSEENTER                    => Attr\SimpleAttribute::class,
        self::ONMOUSELEAVE                    => Attr\SimpleAttribute::class,
        self::ONMOUSEMOVE                     => Attr\SimpleAttribute::class,
        self::ONMOUSEOUT                      => Attr\SimpleAttribute::class,
        self::ONMOUSEOVER                     => Attr\SimpleAttribute::class,
        self::ONMOUSEUP                       => Attr\SimpleAttribute::class,
        self::ONOFFLINE                       => Attr\SimpleAttribute::class,
        self::ONONLINE                        => Attr\SimpleAttribute::class,
        self::ONPAGEHIDE                      => Attr\SimpleAttribute::class,
        self::ONPAGEREVEAL                    => Attr\SimpleAttribute::class,
        self::ONPAGESHOW                      => Attr\SimpleAttribute::class,
        self::ONPAGESWAP                      => Attr\SimpleAttribute::class,
        self::ONPASTE                         => Attr\SimpleAttribute::class,
        self::ONPAUSE                         => Attr\SimpleAttribute::class,
        self::ONPLAY                          => Attr\SimpleAttribute::class,
        self::ONPLAYING                       => Attr\SimpleAttribute::class,
        self::ONPOPSTATE                      => Attr\SimpleAttribute::class,
        self::ONPROGRESS                      => Attr\SimpleAttribute::class,
        self::ONRATECHANGE                    => Attr\SimpleAttribute::class,
        self::ONRESET                         => Attr\SimpleAttribute::class,
        self::ONRESIZE                        => Attr\SimpleAttribute::class,
        self::ONREJECTIONHANDLED              => Attr\SimpleAttribute::class,
        self::ONSCROLL                        => Attr\SimpleAttribute::class,
        self::ONSCROLLEND                     => Attr\SimpleAttribute::class,
        self::ONSECURITYPOLICYVIOLATION       => Attr\SimpleAttribute::class,
        self::ONSEEKED                        => Attr\SimpleAttribute::class,
        self::ONSEEKING                       => Attr\SimpleAttribute::class,
        self::ONSELECT                        => Attr\SimpleAttribute::class,
        self::ONSLOTCHANGE                    => Attr\SimpleAttribute::class,
        self::ONSTALLED                       => Attr\SimpleAttribute::class,
        self::ONSTORAGE                       => Attr\SimpleAttribute::class,
        self::ONSUBMIT                        => Attr\SimpleAttribute::class,
        self::ONSUSPEND                       => Attr\SimpleAttribute::class,
        self::ONTIMEUPDATE                    => Attr\SimpleAttribute::class,
        self::ONTOGGLE                        => Attr\SimpleAttribute::class,
        self::ONUNHANDLEDREJECTION            => Attr\SimpleAttribute::class,
        self::ONUNLOAD                        => Attr\SimpleAttribute::class,
        self::ONVOLUMECHANGE                  => Attr\SimpleAttribute::class,
        self::ONWAITING                       => Attr\SimpleAttribute::class,
        self::ONWHEEL                         => Attr\SimpleAttribute::class,
    ];
}//end class
